#pragma once

#include "card.h"

#define CC(a1,a2,a3,a4,a5,a6,a7,a8,e,s,...) \
    {{0x##a1,0x##a2,0x##a3,0x##a4,0x##a5,0x##a6,0x##a7,0x##a8},0x##e,0x##s,__VA_ARGS__}

#define CC_PLACEHOLDER \
    CC(ff,ff,ff,ff,ff,ff,ff,ff, 00,aaaa, 1, "Placeholder")

PROGMEM const Card CARDS [] = {
    CC_PLACEHOLDER,

    // 01 - 10
    CC(38,47,82,84,84,82,47,38, 24,1234, "Kitty Cat", "BASIC FELINE. CLAWS, FUR, ETC."),
    CC(76,89,8d,81,8e,81,4d,32, 25,567A, "Bunny", "CUTE, FLUFFY, AND MOSTLY HARMLESS."),
    CC(38,44,82,81,81,87,49,32, 24,89AA, "Water Sprite"),
    CC(77,89,c2,c4,84,82,49,37, 24,1111, "Dingo"),
    CC(1c,22,e1,a1,a1,e1,22,1c, 23,2327, "Mushroom"),
    CC(b8,c4,44,44,c4,59,e3,3e, 14,4734, "Scorpion"),
    CC(fc,42,81,41,81,41,82,fc, 23,8888, "Ghost"),
    CC(38,44,82,81,81,81,42,3c, 24,1214, "Slime"),
    CC(7b,c5,c2,84,44,32,0d,03, 14,5538, "Jackal"),
    CC(3e,45,c3,c2,82,83,45,3e, 24,1839, "Bear"),

    // 11 - 20
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 21 - 30
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 31 - 40
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 41 - 50
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 51 - 60
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 61 - 70
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 71 - 80
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 81 - 90
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,

    // 91 - 100
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
    CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER, CC_PLACEHOLDER,
};
