#pragma once

#define STATE_USER_SELECT 1
#define STATE_USER_HOVER 2
#define STATE_ENEMY_SELECT 3

#define STATE_COLLECTION_INSPECT 10

#define BOUND_GAME_LOWER STATE_USER_SELECT
#define BOUND_GAME_UPPER STATE_ENEMY_SELECT

